services:
  shelfmark-lite:
    image: ghcr.io/calibrain/shelfmark-lite:sha256-d3b543487b79031aec7b6b9fae06c6e7c296965e10d46d5f711b0a3c52c1335c
    container_name: shelfmark-lite
    environment:
      EXT_BYPASSER_URL: ${FLARESOLVERR_URL}
      PUID: 1000
      PGID: 1000
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      - /srv/homelab/shelfmark/books:/books # Default destination for book downloads
      - /srv/homelab/shelfmark/config:/config # App configuration
      # Required for torrent / usenet - path must match your download client's volume exactly
      # - /path/to/downloads:/path/to/downloads
